### ISSUE TITLE
Error installing Swish: unable to connect to github.com:

### ISSUE THREAD

**Issue by DalekDave** [SWI-Prolog/swish#151] opened 2022-07-11 20:43 UTC
Hello! First, thank you for your work on Swish! :)

I am following the instructions in the file /README.md

I actually have yarn, npm and node installed and running on my server. (please see the versions below).

When I run 'yarn' from the top directory of my Swish git clone, I am getting the error that a connection could not be made to github.com (the connection timed out).

**How can I overcome this please?**

(I have previously had Swish up and running on this server, but had to do a total server  re-installation with no access to a backup. So I know it _can_ work.)

Below is the command line output leading up to the error. 

```
root@myserver ~ # npm --version
8.11.0
root@myserver ~ # node --version
v16.16.0
root@myserver ~ # yarn --version
1.22.15
root@myserver ~ # cd /var/www/swish
root@myserver /var/www/swish # ls
LICENSE    TODO.md  config-available  ide.pl      pack          run.pl     swish-node-modules.zip  web
Makefile   VERSION  daemon.pl         lib         package.json  scripts    swish.pl
README.md  client   examples          myswish.pl  profiles      server.pl  test
root@myserver /var/www/swish # yarn
yarn install v1.22.15
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
error Command failed.
Exit code: 128
Command: git
Arguments: ls-remote --tags --heads git://github.com/twitter/typeahead.js.git
Directory: /var/www/swish
Output:
fatal: unable to connect to github.com:
github.com[0: 140.82.121.3]: errno=Connection timed out
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

**Comment by DalekDave** [comment] 2022-07-11 21:20
Update: okay, I got around the problem by using the suggested zip file with the dependencies already installed.
So I have Swish back up and running at https://prolog.collaboration.cafe

I'll be back to continue my past obsession with dark-theming Swish. :)

**But maybe the original error is worth fixing anyway?**

Once again, thank you for your work on Swish and SWI-Prolog! :)

**Comment by JanWielemaker** [comment] 2022-07-12 06:49
Dark theme shall be popular (I can't read it ...)   I guess the problem is a temporary network problem or a yarn issue.  Nothing I can do something against.   Closing ...

**Closed by JanWielemaker** 2022-07-12 06:49 UTC
