### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by triska** [SWI-Prolog/swish#32] opened 2016-04-29 20:09 UTC
When I run the sample query in [**PowWDhGw.pl**](http://swish.swi-prolog.org/p/PowWDhGw.pl), I get:

<pre>
Internal server error

Unknown error term: assertion_error(fail,pengines:event_term_to_json_data(success('6a9daf86-e6c8-4579-ba05-3ff78a491347',[json{'A':_G3581,'B':_G3619,'C':_G3654,'Residuals':'$residuals'([])}],0.0007278980000000046,false),_G3560,'json-html'))
</pre>

**Comment by JanWielemaker** [comment] 2016-04-30 09:06
Hmm.  It is not a swish issue.  After some backtracking, this shows the same (in the normal toplevel)

```{prolog}
?- use_module(library(clpb)).
?- sat(card([1,2],[A,B+ ~C])), recorda(s, t(A,B,C)).
sat(card([1,2],[A,B+ ~C])), recorda(s, t(A,B,C)).
?- recorded(s, T).
false.
?- recorded(s, T), writeln(T).
t(_G28195,_G28233,_G28268)
```
It gets weirder.  From the above I concluded the recorded database is broken.  But, the next interaction suggests there is nothing wrong with recorda/recorded:

```{prolog}
?- sat(card([1,2],[A,B+ ~C])), T = t(A,B,C),
    recorda(s2, T), recorded(s2, T2),
   T =@= T2.
T = t(A, B, C),
T2 = t(_G32779, _G32780, _G32781),
sat(1#A*B*C#A*C#B*C#C),
sat(1#_G32779*_G32780*_G32781#_G32779*_G32781#_G32780*_G32781#_G32781).
```

But after the above:

```{prolog}
?- recorded(s2, T2).
false.
```

Note that I started suspecting recorda/recorded as in SWISH the rendering is done by a secondary thread and the answer is transferred using thread_send_message/2, which in the end uses the same intermediate term representation as the recorded database.

At first sight, the above suggests recorda/recorded is just fine and the problem is somewhere in clpb's copy_term/3 that needs more than just the attributes.  I think that is something you can easier figure out than I.

**Comment by triska** [comment] 2016-04-30 09:30
To safely mix constrained variables with the database, one should use `copy_term/3` to project the constraints to residual goals, and assert the variables together with the constraints (instead of the attributes). `copy_term/3` gives you a copy together with the goals that, when called, reinstate the constraints on the copy. So, in the cases you show, I would assert a pair&nbsp;`Vs-Gs`, like this:
<pre>
?- sat(card([1,2],[A,B+ ~C])),
   Vs0 = [A,B,C],
   <b>copy_term(Vs0, Vs, Gs),
   recorda(s, Vs-Gs)</b>.
Vs0 = [A, B, C],
Vs = [_G347, _G350, _G353],
Gs = [clpb:sat(1#_G347*_G350*_G353#_G347*_G353#_G350*_G353#_G353)],
sat(1#A*B*C#A*C#B*C#C).
</pre>

Later, I can safely fetch the stored goals:

<pre>
?- recorded(s, [A,B,C]-Gs).
Gs = [clpb:sat(1#A*B*C#A*C#B*C#C)].
</pre>

This works exactly as intended.

In the case of CLP(B), it is **not** sufficient to simply record the variables that are directly reachable! This is because the attributes of those variables refer to further variables that have again attributes to store certain data structures that must be accessible from all variables that are involved in SAT&nbsp;constraints. You can fetch these variables with&nbsp;`term_attvars/2`. For example:

<pre>
?- <b>sat(A+B)</b>, term_attvars(A-B, [_,<b>C</b>,_]), get_attrs(C, As).
As = att(clpb_bdd, A+B-node(2, A, node(1, B, 0, 1, _G1798), 1, _G1792), []),
sat(A=\=A*B#B).
</pre>
(In this case, I knew beforehand that <b>C</b> would occur at this place.)

**Comment by triska** [comment] 2016-04-30 10:58
I have found a simpler test case:

<pre>
?- sat(card([1], [A+B])), recorda(s, [A,B]).
sat(A=\=A*B#B).

?- recorded(s, Ts).
false.
</pre>

I have also traced down the problem a bit: In the projection to residual goals of the *second* query, a variable is encountered that lacks a `clpb_hash` attribute, and therefore the projection fails. I find this quite strange, since all CLP(B) variables soon get a `clpb_hash` attribute, and this attribute should also be copied if everything works as expected. Note though that `clpb_hash` in itself yields no residual goals, because this attribute is only used internally in the library. For finding more about this, you can comment out all the `attribute_goals//1` nonterminals at the end of `library(clpb)`.

You then get for example:

<pre>
?- sat(card([1],[A+B])).
sat(A=\=A*B#B),
put_attr(A, clpb_hash, t(...)),
put_attr(B, clpb_hash, t(...)).
</pre>
This shows that the `clpb_hash` attribute is attached to both variables.

**Comment by JanWielemaker** [comment] 2016-04-30 12:16
Seems a bit odd that attributes are lost.   Sure that is no artefact of the toplevel?  The following
also suggest this is not the problem, but something quite simple is:

```{prolog}
?- sat(card([1], [A+B])), nb_delete('$clpb_next_var').
false.
```

And, symmetric:

```{prolog}
?- sat(card([1], [A+B])), recorda(s3, [A+B]).
sat(A=\=A*B#B).

?- nb_setval('$clpb_next_var', 3), recorded(s3, X).
X = [_G181+_G182],
sat(_G181=\=_G181*_G182#_G182).
```

And yes, recorda/recorded do copy attributes of variables in attribute values. etc.  It only breaks if you creates relations to global variables other then being reachable from the term.  For example. you do `put_attr(V, x, myvar)` and get the value using `b_getval(myvar, Value)`.

This doesn't imply that passing the attributes rather than using copy_term/3 inside the Pengine  is a good idea.  I haven't made up my mind on this.

**Comment by JanWielemaker** [comment] 2016-04-30 14:12
Related, looking at `attvar_residuals//2` in `attvar.pl`, now we have

```{prolog}
	    ;	{ current_predicate(Module:attribute_goals//1) }
	    ->	{ phrase(Module:attribute_goals(V), Goals) },
		list(Goals)
	    ;	[put_attr(V, Module, Value)]
```

Shouldn't we either move the phrase/2 into the condition or raise an exception of the phrase/2 fails.  I can remember similar cases where debugging is rather hard due to this hook failing.

Yet another choice might be to print a warning if the hook fails and use `put_attr(V, Module, Value)` to succeed.   I don't like printing warnings in general.  In this case it both tells you something is wrong and still provides a basically correct answer that also gives a hint to the author of the hook.   Of course, using `print_message/2`.

**Comment by triska** [comment] 2016-04-30 17:57
I agree that debugging `attribute_goals//1` can become too hard currently. I also remember I had several issues with the GUI&nbsp;tracer when debugging CLP(B)'s `attribute_goals//1`, because the code I meant to debug was implicitly invoked in the GUI&nbsp;tracer itself when showing the residual goals. I'm not sure what the best solution is in this case. Moving the call into the condition would solve some aspects. But the GUI&nbsp;tracer should also provide a way to disable the hook in my view.

Regarding `$clpb_next_var`: This is a global variable that CLP(B) implicitly relies on, and it is not shown in residual goals because it can normally be safely revoked on backtracking. Also in this case, I do not know how to best fix is. I think reasoning about residual goals (as opposed to attributes) is the only safe way out in such cases.

**Comment by JanWielemaker** [comment] 2016-04-30 18:46
Moved `attribute_goals//1`.  At least that avoids hard-to-explain failures.  Might also improve debugging the hook as the debugger can now rely on copy_term/3 to succeed.  Not sure though.  
Surely errors from copy_term/3 are still problematic.  Some low-level infrastructure is hard to debug with high level debuggers :(  

As for `$clpb_next_var`, relying in this variable seems a little fragile to me.   What about things
like this?   Is there no reasonable way around relying on this global var?

    some_clpb_call(X),
    some_clpb_call(Y),
    copy_term(X, XC, G)

**Comment by triska** [comment] 2016-04-30 20:23
Each CLP(B) variable must get a unique integer index. This must somehow be possible. Currently, the global variable is used for this. If there were another way, that would also be OK. Note that on backtracking, the global index can be reset, because constraints are reset as well. `copy_term/3` always produces residual constraints that are equivalent to the constraints that are already posted. The global counter is kept completely internal and never arises in residual goals.

**Comment by JanWielemaker** [comment] 2016-04-30 21:01
Probably naive, but I'd assume that each clp(b) variable in the answer already has such an integer?
Right now, you also get results like this:

```{prolog}
?- findall(A+B, sat(card([1], [A+B])), L).
L = [_G1327+_G1328],
put_attr(_G1327, clpb, index_root(0, _G1338)),
put_attr(_G1328, clpb, index_root(1, _G1338)).
```

Would have been `false` this morning ...  I know using findall/3 with constraints is not brilliant, but if you can work around this in a sensible way, the above can make sense too.

**Comment by triska** [comment] 2016-05-01 08:17
Yes, each CLP(B) variable has such an index, as the first argument of `index_root/2`. The problem is that when parsing a new variable and the counter is reset, IDs that are used for other variables are inadvertently *reused*.

A patch that uses `nb_setval/2` instead of `b_setval/2` in CLP(B) when incrementing IDs is available from [https://github.com/triska/swipl-devel/commit/f5c748a7d52cbf06e0382e05f6dc9fe66fa6cb73](https://github.com/triska/swipl-devel/commit/f5c748a7d52cbf06e0382e05f6dc9fe66fa6cb73).

With this change, the `recorda/2` and `recorded/2` works in our examples. My preference is still to be able to use `b_setval/2`, and let SWISH work on the residual goals alone, not only for the sake of CLP(B) but also for all other constraint libraries that do not know about&nbsp;SWISH. Still, I have made this change to be able to test this. Apparently though, that change in itself is not sufficient: I see the same error in my local SWISH&nbsp;instance even with this change applied.

**Comment by JanWielemaker** [comment] 2016-05-01 08:50
Using a non-backtrackable variable will help for the same-thread examples, but won't help for SWISH as the copy_term/3 happens in another thread.  You either need to find a way to avoid dependency on this variable for the hook or see if/when Pengines will do the copy_term/3.  I'm still not sure this is a good idea in the first place.  If it is, it probably requires changes to the pengines basics and protocol.
This is not going to happen anytime soon, unless I think of a really elegant way of doing this.

Given that the attribute_goals//1 of clpb is rather slow anyway, can't you figure out where to start numbering using a rather simple scan?   That would make clpb answers self-contained, so you can copy them around in the same process, either using findall or sending them to other threads.

**Comment by triska** [comment] 2016-05-01 09:40
> Given that the attribute_goals//1 of clpb is rather slow anyway, can't you figure out where to start numbering using a rather simple scan? That would make clpb answers self-contained, so you can copy them around in the same process, either using findall or sending them to other threads.

I have now done this in this patch: https://github.com/triska/swipl-devel/commit/ed34c08580f04f5af3dd8ca6dc5b9d2c628d178d

Again, the `recorda/2` and `recorded/2` examples now work, and again this does not seem to be sufficient for SWISH: In SWISH, I now get an error from the renderer  (type error: `clpb_next_id/2`: evaluable expected, found `[]`). Maybe I must somehow use the non-backtrackable versions for the renderer to work with this? But for CLP(B) itself, I want to be able to reuse IDs.

**Comment by JanWielemaker** [comment] 2016-05-01 09:50
I think this is related to this behaviour:

```{prolog}
?- b_setval(s, 0), fail ; b_getval(s,X).
X = [].
```

I.e., backtracking over the creation of a backtrackable global var resets it to [].  I've always advocated for fully separating backtrackable and non-backtrackable global variables, where the backtrackable version is removed when backtracking over its creation.  This was not an option.  Thus, they are basically the same and only the _assignment_ is backtrackable or not.   I think you can fix your issue by using nb_setval(var, 0) in the creation handler and keep the b_[sg]etval for the update.

... and add a remark that this is odd ...

**Comment by triska** [comment] 2016-05-01 10:38
Thank you, I have pushed changes that make all this work, please restart SWISH with this version.

**Comment by JanWielemaker** [comment] 2016-05-01 11:11
And a nice picture  [**PowWDhGw.pl**](http://swish.swi-prolog.org/p/PowWDhGw.pl) now gives :)

**Closed by JanWielemaker** 2016-05-01 11:11 UTC
